#!/usr/bin/env python3
"""
Generate Astro redirect configuration from registry database.

This script reads the url_redirects table and generates a TypeScript file
that can be imported into astro.config.ts.

Usage:
    python3 tools/scripts/generate_astro_redirects.py

Output:
    data.mn/src/redirects.generated.ts

Run this script:
- After adding/changing redirects
- Before building the Astro site
- As part of the build pipeline

See docs/principles/url-stability.md for full documentation.
"""

import json
import sys
from pathlib import Path

# Add tools directory to path for registry import
SCRIPT_DIR = Path(__file__).parent
TOOLS_DIR = SCRIPT_DIR.parent
sys.path.insert(0, str(TOOLS_DIR))

from registry import Registry

# Output location
DATA_MN_DIR = TOOLS_DIR.parent / "data.mn"
OUTPUT_FILE = DATA_MN_DIR / "src" / "redirects.generated.ts"


def generate_redirects():
    """Generate TypeScript redirect configuration"""
    registry = Registry()

    # Get redirects from database
    redirects = registry.export_redirects_for_astro()

    # Generate TypeScript content
    ts_content = '''// Auto-generated by tools/scripts/generate_astro_redirects.py
// Do not edit manually - changes will be overwritten
//
// To add redirects:
//   python -m registry add-redirect <old-slug> --target <dataset-id> --reason "..."
//   python tools/scripts/generate_astro_redirects.py
//
// See docs/principles/url-stability.md for URL stability principles

export const generatedRedirects: Record<string, string> = '''

    ts_content += json.dumps(redirects, indent=2, ensure_ascii=False)
    ts_content += ';\n'

    # Add type export
    ts_content += '''
export type RedirectMap = typeof generatedRedirects;
'''

    return ts_content, len(redirects)


def main():
    """Main entry point"""
    print("Generating Astro redirects...")

    ts_content, count = generate_redirects()

    # Ensure output directory exists
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    # Write output
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(ts_content)

    print(f"✅ Generated {OUTPUT_FILE}")
    print(f"   {count} redirects configured")

    if count == 0:
        print("\n   Note: No redirects in database yet.")
        print("   Redirects are created automatically when renaming URLs.")
        print("   Use: python -m registry rename <id> <new-slug> --reason '...'")


if __name__ == '__main__':
    main()
