// Auto-generated by tools/scripts/generate_astro_redirects.py
// Do not edit manually - changes will be overwritten
//
// To add redirects:
//   python -m registry add-redirect <old-slug> --target <dataset-id> --reason "..."
//   python tools/scripts/generate_astro_redirects.py
//
// See docs/principles/url-stability.md for URL stability principles

export const generatedRedirects: Record<string, string> = {};

export type RedirectMap = typeof generatedRedirects;
